### PR TITLE
Added Spanish localization

### PR DESCRIPTION
**Pull request by RadAurum**
- Added spanish json
- Added small fix for text width in Settings -> Hierarchy options on spanish selected

### CODE REVIEW

**Comment by momo-the-monster** [comment]
recheck

**Comment by RadAurum** [comment]
@momo-the-monster can you provide me the link of the issue link? or i just sign here?

**Comment by momo-the-monster** [comment]
> @momo-the-monster can you provide me the link of the issue link? or i just sign here?

Here is the comment to read and reply to, thanks!

https://github.com/vrchat-community/EasyQuestSwitch/pull/19#issuecomment-1920295310

**Comment by RadAurum** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by JordoVR — APPROVED** [review]

**Pull request merged**
